apiVersion: v1
kind: ServiceAccount
metadata:
  name: restart-mydeployments
  namespace: ingress-namespace

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: restart-mydeployments
  namespace: ingress-namespace
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["myapplication"]
    verbs: ["get", "patch"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["myapplication1"]
    verbs: ["get", "patch"]
 
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: restart-mydeployments
  namespace: ingress-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-mydeployments
subjects:
  - kind: ServiceAccount
    name: restart-mydeployments
    namespace: ingress-namespace
  
---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: cronjob-a
  namespace: ingress-namespace
spec:
  concurrencyPolicy: Forbid
  schedule: "0 */5 * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: restart-mydeployments
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'myapplication'
                - 'myapplication1'