apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-a
  namespace: ingress-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapplication
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50