apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-hello
  namespace: monitoring
spec:
  selector:
    matchLabels:
      # Target app service
      app: web2
  endpoints:
    - interval: 15s
      path: '/metrics'
      port: "80"
      scheme: http
  namespaceSelector:
    matchNames:
      - ingress-namespace